---
- name: Add rpm key
  rpm_key:
    key: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add rpm repository
  yum_repository:
    name: nginx
    baseurl: https://nginx.org/packages/mainline/centos/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Repository
    enabled: yes
    gpgcheck: yes
