---
- name: Install python3 python3-pip
  package:
    name:
      - python3
      - python3-pip
      - unzip
    state: present

- name: ensure directory exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/v2ray
    - /etc/v2ray

- name: Get latest release of v2ray
  shell: |
    set -o pipefail
    git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' http://github.com/v2fly/v2ray-core.git 2>/dev/null | tail --lines=1 | cut --delimiter='/' --fields=3
  args:
    executable: /bin/bash
  register: v2ray_latest

- name: get v2ray binary package
  unarchive:
    src: "https://github.com/v2fly/v2ray-core/releases/download/{{ v2ray_latest.stdout }}/v2ray-linux-64.zip"
    dest: /opt/v2ray
    mode: 0755
    remote_src: yes
  when: ansible_architecture == "x86_64"

- name: get v2ray binary package
  unarchive:
    src: "https://github.com/v2fly/v2ray-core/releases/download/{{ v2ray_latest.stdout }}/v2ray-linux-arm64-v8a.zip"
    dest: /opt/v2ray
    mode: 0755
    remote_src: yes
  when: ansible_architecture == "aarch64"

- name: symlink binary files
  file:
    src: "/opt/v2ray/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - v2ray
    - v2ctl

- name: generate v2ray config
  template:
    src: config.json.j2
    dest: /etc/v2ray/config.json
    mode: 0644
  notify:
    - restart v2ray

- name: copy systemd config
  copy:
    src: v2ray.service
    dest: /etc/systemd/system/v2ray.service
    mode: 0644

- name: enable v2ray service
  systemd:
    name: v2ray
    state: started
    daemon_reload: yes
    enabled: yes

- name: mk v2ray log dir
  file:
    path: /var/log/v2ray
    state: directory
    mode: 0755

- name: Touch v2ray access log file
  file:
    path: /var/log/v2ray/access.log
    state: touch
    mode: 0644

- name: Touch v2ray error log file
  file:
    path: /var/log/v2ray/error.log
    state: touch
    mode: 0644
